# Generated by Django 4.1.1 on 2023-01-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=70)),
                ('upvote', models.IntegerField()),
                ('downvote', models.IntegerField()),
            ],
        ),
    ]
