# Generated by Django 4.1.1 on 2023-01-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reactions',
            new_name='Reaction',
        ),
    ]
